project:
  type: website

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: strategic-marketing.qmd
        text: Projects
      - href: resume.qmd
        text: Resume
      - href: contact-us/contact-us.qmd
        text: Contact

format:
  html:
    theme:
      - cosmo
      - theme.scss
    toc: true