project:
  type: website
  output-dir: docs

website:
  google-analytics: G-6CDNWWDT04
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: strategic-marketing.qmd
        text: Projects
      - href: marketing-analytics.qmd
        text: Marketing Analytics
      - href: resume.qmd
        text: Resume
      - href: contact-me/contact-me.qmd
        text: Contact

format:
  html:
    theme:
      - cosmo
      - theme.scss
    toc: true